// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFragments(arg1) {
  return window['go']['main']['App']['DeleteFragments'](arg1);
}

export function FragmentTexts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FragmentTexts'](arg1, arg2, arg3, arg4);
}

export function GetCurrentPage() {
  return window['go']['main']['App']['GetCurrentPage']();
}

export function GetPaginatedData() {
  return window['go']['main']['App']['GetPaginatedData']();
}

export function GetText(arg1) {
  return window['go']['main']['App']['GetText'](arg1);
}

export function GetTotalPages() {
  return window['go']['main']['App']['GetTotalPages']();
}

export function LoadFiles(arg1) {
  return window['go']['main']['App']['LoadFiles'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SetCurrentPage(arg1) {
  return window['go']['main']['App']['SetCurrentPage'](arg1);
}
