// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFragments(arg1:Array<string>):Promise<void>;

export function FragmentTexts(arg1:Array<string>,arg2:string,arg3:number,arg4:number):Promise<Array<main.FragmentMetadata>>;

export function GetCurrentPage():Promise<number>;

export function GetPaginatedData():Promise<Array<main.TextFragment>>;

export function GetText(arg1:number):Promise<main.TextFragment>;

export function GetTotalPages():Promise<number>;

export function LoadFiles(arg1:Array<string>):Promise<Array<main.TextFragment>>;

export function OpenFileDialog():Promise<Array<string>>;

export function SetCurrentPage(arg1:number):Promise<void>;
